import { type NextPage } from "next";
import Head from "next/head";
import Assets from "~/components/Assets";
import Indices from "~/components/Indices";
import UpdateArea from "~/components/UpdateArea";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <UpdateArea />
        <Indices />
        <Assets />
      </>
    </>
  );
};

export default Home;
